### ISSUE TITLE
last_read_state is a float number

### ISSUE THREAD

**Issue by jerryc05** [ZacheryThomas/srpy#6]
the error message below should explain itself quite well:
```
2023-07-12 14:33:31.011 WARNING (MainThread) [smartrent.utils] Traceback (most recent call last):
  File "***/smartrent/utils.py", line 446, in _async_update_state_via_ws
    await device._update(formatted_resp)
  File "***/smartrent/device.py", line 148, in _update
    self._update_parser(event)
  File "***/smartrent/thermostat.py", line 163, in _update_parser
    self._current_temp = int(last_read_state)
ValueError: invalid literal for int() with base 10: '78.4'
```

**Comment by ZacheryThomas** [comment]
Should be fixed in the latest release: https://github.com/ZacheryThomas/smartrent.py/releases/tag/v0.4.2
